#!/bin/bash
# SPDX-FileCopyrightText: 2021 Red Hat, Inc.
#
# SPDX-License-Identifier: MIT

die() {
    echo "ERROR: ${1}" >&2
    exit 1
}

# Default to debug, search for release
debug="./target/debug/clevis-pin-tpm2"
release="./target/release/clevis-pin-tpm2"
if [[ -f "${debug}" ]]; then
    bin="${debug}"
elif [[ -f "${release}" ]]; then
    bin="${release}"
else
    die "No binary found. Run cargo build first"
fi

(
	cd ../clevis-pin-tpm2-signtool
	go build
)
(
	cd tests
	rm -f policy_broken.json policy_working.json privatekey.pem publickey.json
	../../clevis-pin-tpm2-signtool/clevis-pin-tpm2-signtool <policy_working.yaml >policy_working.json
	../../clevis-pin-tpm2-signtool/clevis-pin-tpm2-signtool <policy_broken.yaml >policy_broken.json
)
echo "Working: with Policy" \
    | "${bin}" encrypt '{"use_policy": true, "policy_pubkey_path":"./tests/publickey.json", "policy_ref": "", "policy_path": "./tests/policy_working.json"}' \
    | "${bin}" decrypt
echo "Working: with Policy (no use_policy)" \
    | "${bin}" encrypt '{"policy_pubkey_path":"./tests/publickey.json", "policy_ref": "", "policy_path": "./tests/policy_working.json"}' \
    | "${bin}" decrypt
# Negative test (non-valid policy)
token=$(echo Failed | "${bin}" encrypt '{"use_policy": true, "policy_pubkey_path":"./tests/publickey.json", "policy_ref": "", "policy_path": "./tests/policy_broken.json"}')
res=$(echo "$token" | "${bin}" decrypt 2>&1)
ret=$?
if [ $ret == 0 -a "$res" == "Failed" ]
then
	echo "Managed to decrypt with invalid policy"
	exit 1
elif [ $ret == 0 ];
then
	echo "Success returned but not decrypted"
	exit 1
elif [[ $res =~ Esys_VerifySignature_Finish() ]]
then
	echo "Working: with policy with invalid digest"
else
	echo "Something went wrong: $res"
	exit 1
fi
